#!/bin/bash
#SBATCH -A SMU-Math-6370    # account name
#SBATCH -J driver_omp_t1    # job name
#SBATCH -o t1_out.%j        # output file
#SBATCH -e t1_err.%j        # error file
#SBATCH -N 1                # total nodes requested
#SBATCH -n 1                # total MPI tasks requested
#SBATCH -p normal           # queue name
#SBATCH -t 00:02:00         # total time requested <hh:mm:ss>

export OMP_NUM_THREADS=1
ibrun ./driver.exe
