#!/bin/bash
#
# FILE: omp_bug3fix_BASH
# DESCRIPTION:
#    This script is used to set the thread stack size limit to accomodate
#    the omp_bug3 example. The example code requires @16MB per thread. For
#    safety, this script sets the stack limit to 20MB. Note that the way
#    to do this differs between architectures. 
# AUTHOR: Blaise Barney  01/12/04
# LAST REVISED: Daniel R. Reynolds  02/13/15

# This is for all systems
ulimit -s unlimited

# This is for OpenMP version 3 compliant systems 
export OMP_STACKSIZE=20000000

# This is for IBM AIX systems
export XLSMPOPTS="stack=20000000"

# This is for Linux systems 
export KMP_STACKSIZE=20000000

# This is for HP/Compaq Tru64 systems
export MP_STACK_SIZE=20000000

# Now call the executable - change the name to match yours
omp_bug3.exe
