###################################################################
#  Makefile for Lab 1
#
#  Daniel R. Reynolds
#  SMU Mathematics
#  Math 4370/6370
###################################################################

main.exe : main.cpp
	g++ -o main.exe main.cpp


####### End of Makefile #######
